{
  "postgreConfig":
    {
      "host": "localhost",
      "port": "5432",
      "user": "testUser",
      "password": "password",
      "dbname": "wbCourseL0",
      "connectionTimeout": 5,
    },
  "kafka":
    {
      "host": "localhost",
      "kafkaPort": "9092",
      "zookeeperPort": "2182",
      "readTimeout": "10",
      "writeTimeout": "10",
    },
  "cache": 
    { 
      "objsInCache": 100,
      "cacheBuffer" : 5 
    },
}
